spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/userproductmanagement
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
  application:
    name: ITEM-COMMENTS_SERVICE
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
server:
  port: '9900'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
